### PR TITLE
Remove interval update of hashrate which changes status of @oclif/cor…

### LINKED ISSUE #904: Ironfish miner logs when no TTY or TERM=dumb are missing line breaks
### What happened?

I am running ironfish through systemd. When I run `journalctl -f -u ironfish` the logs show, but it gets confused by your pretty log output and puts a bunch of the output together without any line breaks.

When I run the miner directly (without systemd), the logs look correct.

Is there some way to disable this pretty paging?

### Version

v0.1.18

### Relevant log output

```shell
$ journalctl -f -u ironfish
-- Journal begins at Tue 2022-01-11 22:12:20 UTC. --
Jan 15 21:41:54 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 32... 47872 H/sMining block 69287 on request 32... 47882 H/sMining block 69287 on request 32... 47892 H/sMining block 69287 on request 32... 47922 H/sMining block 69287 on request 32... 47853 H/sMining block 69287 on request 32... 49890 H/sMining block 69287 on request 32... 49811 H/sMining block 69287 on request 32... 49851 H/sMining block 69287 on request 32... 49732 H/s
Jan 15 21:41:54 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 33... 49791 H/s
Jan 15 21:42:04 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 33... 47801 H/sMining block 69287 on request 33... 47742 H/sMining block 69287 on request 33... 45850 H/sMining block 69287 on request 33... 45840 H/sMining block 69287 on request 33... 47840 H/sMining block 69287 on request 33... 47910 H/sMining block 69287 on request 33... 47960 H/sMining block 69287 on request 33... 49880 H/s
Jan 15 21:42:04 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 34... 49851 H/s
Jan 15 21:42:14 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 34... 47851 H/sMining block 69287 on request 34... 47801 H/sMining block 69287 on request 34... 45803 H/sMining block 69287 on request 34... 45852 H/sMining block 69287 on request 34... 45892 H/sMining block 69287 on request 34... 47872 H/sMining block 69287 on request 34... 47912 H/sMining block 69287 on request 34... 49910 H/sMining block 69287 on request 34... 49940 H/s
Jan 15 21:42:14 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 35... 49920 H/s
Jan 15 21:42:24 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 35... 45934 H/sMining block 69287 on request 35... 45874 H/sMining block 69287 on request 35... 45864 H/sMining block 69287 on request 35... 45874 H/sMining block 69287 on request 35... 49870 H/sMining block 69287 on request 35... 49930 H/sMining block 69287 on request 35... 49920 H/sMining block 69287 on request 35... 49900 H/s
Jan 15 21:42:24 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 36... 49870 H/s
Jan 15 21:42:34 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 36... 45886 H/sMining block 69287 on request 36... 45856 H/sMining block 69287 on request 36... 45866 H/sMining block 69287 on request 36... 45876 H/sMining block 69287 on request 36... 45946 H/sMining block 69287 on request 36... 49940 H/sMining block 69287 on request 36... 49980 H/sMining block 69287 on request 36... 49990 H/s
Jan 15 21:42:34 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 37... 49970 H/s
Jan 15 21:42:44 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 37... 45970 H/sMining block 69287 on request 37... 45890 H/sMining block 69287 on request 37... 45880 H/sMining block 69287 on request 37... 45870 H/sMining block 69287 on request 37... 49870 H/sMining block 69287 on request 37... 49920 H/sMining block 69287 on request 37... 49910 H/sMining block 69287 on request 37... 47920 H/s
Jan 15 21:42:44 i-016c263f8eee3fe8c ironfish.sh[14481]: Mining block 69287 on request 38... 47950 H/s
```

### PR DESCRIPTION
**Pull request by Kupuyc**
## Summary
Fixes #904.

There is bunch of messages problem in log file (see #904 for details). In tty mode all fine but viewing miner logs by journalctl problematically a little.

I removed interval update of action status which caused problem - we did updates too often and @oclif/core wrote them all to file. We don't need to update hashrate so often - it's ok to update it every onStartMine event which firing every [MINING_DIFFICULTY_CHANGE_TIMEOUT](https://github.com/iron-fish/ironfish/blob/6b587082e0d930be6b4a6c176d13820ccc1d07db/ironfish/src/mining/director.ts#L24) msec (every 10 sec atm).

After removal of code logs looks clean and shiny (tty is ok as well):

```
Feb 13 15:29:19 HOME-wsl yarn[128087]: 3:29:19 PM - Found 0 errors. Watching for file changes.
Feb 13 15:29:19 HOME-wsl yarn[170924]: $ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run miners:start -t 1
Feb 13 15:29:24 HOME-wsl yarn[170962]: Starting to mine with 1 thread
Feb 13 15:29:38 HOME-wsl yarn[170962]: Waiting for director to send work....
Feb 13 15:29:38 HOME-wsl yarn[170962]: Mining block 111661 on request 1... 0 H/s (0)
Feb 13 15:29:48 HOME-wsl yarn[170962]: Mining block 111661 on request 2... 4.51 MH/s (4516000)
Feb 13 15:29:58 HOME-wsl yarn[170962]: Mining block 111661 on request 3... 4.48 MH/s (4484000)
Feb 13 15:30:08 HOME-wsl yarn[170962]: Mining block 111661 on request 4... 4.60 MH/s (4604000)
Feb 13 15:30:18 HOME-wsl yarn[170962]: Mining block 111661 on request 5... 4.54 MH/s (4549090)
Feb 13 15:30:28 HOME-wsl yarn[170962]: Mining block 111661 on request 6... 4.58 MH/s (4583090)
Feb 13 15:30:38 HOME-wsl yarn[170962]: Mining block 111661 on request 7... 4.71 MH/s (4716000)
Feb 13 15:30:46 HOME-wsl yarn[170962]: Mining block 111662 on request 8... 4.72 MH/s (4722000)
Feb 13 15:30:56 HOME-wsl yarn[170962]: Mining block 111662 on request 9... 4.74 MH/s (4743052)
Feb 13 15:31:06 HOME-wsl yarn[170962]: Mining block 111662 on request 10... 4.68 MH/s (4686000)
```
## Testing Plan
Well... run `yarn test`? `¯\_(ツ)_/¯`

## Breaking Change
Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by dguenther** [comment]
Could you disable the interval conditionally using the TTY checks from `oclif`? Otherwise I suspect TTY users are going to report a bug when they see their hashpower stay at 0 for the first several seconds. These two lines:

https://github.com/oclif/core/blob/d7067d13c7d80c9e0064455c27ac1ebb6ee53fd2/src/cli-ux/config.ts#L19

https://github.com/oclif/core/blob/d7067d13c7d80c9e0064455c27ac1ebb6ee53fd2/src/cli-ux/config.ts#L21

It'd be nice to have them in a utility file somewhere so we could use them in multiple commands, but I don't think it's strictly necessary for this PR.

**Comment by Kupuyc** [comment]
@dguenther yep, sure. Sorry, I missed your message.

There is one little problem around: in any case we will see 0 hashrate at least 2 seconds in theory and 3-4 seconds on practice. We launch `setInterval` [here](https://github.com/Kupuyc/ironfish/blob/4d153b2aa205b245957cac613ba72be8ef05cdf3/ironfish/src/metrics/meter.ts#L72). Due of its nature `setInterval` waits first and run callback when timer ends. It is 1st second. Due condition [here](https://github.com/Kupuyc/ironfish/blob/4d153b2aa205b245957cac613ba72be8ef05cdf3/ironfish/src/metrics/meter.ts#L101) we wait 2nd second. Seems like there are some race in code bcos real lag when hashrate begins update about 3-4 seconds.

What do you think, should we add TTY condition? It will increase UX but not so much.

**Comment by dguenther** [comment]
That's a good point. I'd like to have a function containing the TTY condition so that we can easily build behaviors for non-TTY code in the future. I think we should use it in this instance to keep the behavior the same for TTY users, even if it's not entirely correct as it is.

I think the hash rate estimation will be reworked by @NullSoldier + @mat-if's mining pool branch, so this might change, but I think it'd be useful to have the TTY condition as a function we can use, even if it ends up being unnecessary in this case.

**Comment by Kupuyc** [comment]
Got it, thank you.


> useful to have the TTY condition as a function we can use

Done as `isTTY` function in utils/terminal.ts. I did check for stdin instead of stderr but as I can see in docs this is acceptable.

**Comment by NullSoldier** [comment]
We are going to give you credit, but were going to close this until we can port this into the new miner. We just deleted the code that this was modifying, but want this code to come over to the new miner.

**Pull request closed without merging**
