### PR TITLE
Fix a bug where tests were timing out

### PR DESCRIPTION
**Pull request by hamza-siddiq**
## Summary
The default timeout value of jest is set to only 5 seconds. This period seems insufficient for some tests that apparently take
longer to execute. This PR changes the timeout to 32 seconds, which should suffice for the current tests. An improvement would be to make this value get set dynamically according to the specs of the computer running the tests.

This is a continuation of a previous PR: https://github.com/iron-fish/ironfish/pull/1895 . For some reason I could not reopen it. Come back here after having a look at that. 

So turns out that the way I solved it is really the recommended way of solving such issues:

IMG-20220808-WA0015
This is from the official documentation of "jest" (the framework used to write unit-tests)
Here is the documentation, if you'd like to have a look at it:
https://jest-bot.github.io/jest/docs/troubleshooting.html

Let me know if this solves the issue. If not, i'll try to work on another way

## Testing Plan
Tested successfully

## Breaking Change
Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.
No
```
[ ] Yes
```
graffiti: ironfishup

### CODE REVIEW

**Comment by wd021** [comment]
[This](https://github.com/iron-fish/ironfish/pull/1895#issuecomment-1201942527) is the reason tests are timing out on your local machine. As @danield9tqh [mentioned](https://github.com/iron-fish/ironfish/pull/1895#issuecomment-1201789088), we should probably not change the timeouts globally.

**Comment by hamza-siddiq** [comment]
Thanks @wd021 wo

**Comment by hamza-siddiq** [comment]
Thanks @wd021. But I do know that. The documentation has a different recommendation though. So wanted to double check that with the team

**Comment by danield9tqh** [comment]
Yea that documentation makes sense if we have tests that are long running that we want to keep. In this case though the long running tests are not tests that we want to be long running, they are long running because we haven't gotten around to making them better yet. The real fix is to make those specific tests faster or remove them. If we increase the timeout for all tests globally we will miss other cases where tests are running too long. I will close this PR for that reason

**Pull request closed without merging**
