### PR TITLE
remove custom eror message

### PR DESCRIPTION
**Pull request by aditya-manit**
## Summary

Remove custom error message to show config key

Yup automatically gives an appropriate error message with key name and error message, if a custom error message is defined - it will become our responsibility to add the key name in that custom error message.

Here a custom error message was defined without a key name, so in case on error in key value. We were just getting:

`Error: Invalid URL` -> with no idea which key it is for

Removing the custom message which automatically fix the issue
`Error: explorerBlocksUrl must be a valid URL
`
## Testing Plan

Tested on local

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

No

### CODE REVIEW

**Comment by mat-if** [comment]
Hi @aditya-manit, pull requests need to be opened against the staging branch for this repo as outlined here: https://github.com/iron-fish/ironfish/blob/master/CONTRIBUTING.md#contributor-workflow

Can you please update this?

**Comment by aditya-manit** [comment]
I see, updated

**Comment by aditya-manit** [comment]
oh wait, looks like staging and master differs a lot, will fix it in sometime

**Comment by aditya-manit** [comment]
Closed this and created a different PR

**Comment by aditya-manit** [comment]
Check this please: https://github.com/iron-fish/ironfish/pull/2606

**Pull request closed without merging**
