### PR TITLE
Switch blake3 to native addon

### PR DESCRIPTION
**Pull request by dguenther**
## Summary

The blake3 package doesn't seem to ship a native addon that works properly in node 16, so let's try blake-hash instead.

## Testing Plan

Manually tested by mining on a chain, and existing tests should pass.

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by sureshvenkata12** [comment]
did you notice any changes in the hashrate?

**Comment by dguenther** [comment]
I tested on a mac laptop and it certainly seems quicker. Our hashrate display fluctuates all over the place, and I'm not 100% sure it's working as expected, but on average it did seem to stabilize at a higher number.

**Comment by NullSoldier** [comment]
Tested manually

**Review by NullSoldier — APPROVED** [review]

**Comment by gjfrn** [comment]
Am pleased to report that this resolves https://github.com/iron-fish/ironfish/issues/732 with hashrates now at an expected level of improvement, compared with the 0.1.10 change which did not result in any meaningful performance improvement.

**Comment by sureshvenkata12** [comment]
@gjfrn how much improvement have you got?

**Comment by gjfrn** [comment]
> @gjfrn how much improvement have you got?
As per #732, looks to be about 50%+ higher hashrate across 3900X, 3700X and 3600.

**Comment by Kupuyc** [comment]
There are many complains about significant drop of hashrate (40-50%). For me it dropped from 5 mh/s to 3mh/s (lscpu shows AMD EPYC 7282).

**Pull request merged**
