### PR TITLE
Update docker-compose configuration

### PR DESCRIPTION
**Pull request by etretien**
## Summary
Updated the main (non-dev) `docker-compose.yml` to newer version 3.7, for it to be consistent with the `docker-compose.dev.yml` intended for developers running new networks. The reason here is that I tried to use the dev version to run a public testnet node (being more used to 3.x in general), missed the `bootstrap=''` flag and lost some time trying to figure out why it doesn't sync with the network. Pure my fault, but I thought that some people might do it too if we don't make more it more intuitive.

Also, added `-v` flag to the miner start command for verbose log output.

Documentation was also updated.

## Testing Plan
Tested manually on 4 servers with public testnet nodes. No automated tests due to no changes in application code.

## Breaking Change

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by dguenther** [comment]
If you're interested in updating the docs or commands to improve the existing docker-compose files, feel free, but we'd rather leave support for the older 2.4 version -- In the past we had someone add support for that version because (I believe) some Linux distros still ship older versions of Docker (https://github.com/iron-fish/ironfish/pull/555)

**Comment by etretien** [comment]
True, that's why docker official documentation recommends installing from docker repositories instead of OS native ones.
Maybe I could leave both versions and describe more in the docs, so that older version is supported but not recommended?

**Comment by etretien** [comment]
@dguenther I've moved the older version to a separate docker-compose.legacy.yml config. That would incentivise users to use newer versions while keeping compatibility for those who don't want to update. What do you think?
Alternatively, we could older version in docker-compose.yml, and use another name for newer configuration.

Also, I've included the mining pool section to the compose file (made it for my own use and thought it might be useful to others too). Users are free to comment/remove sections that they don't need on a particular machine.

Updated the docs too.

**Comment by dguenther** [comment]
I'd rather not support multiple docker-compose files -- the 2.4 version should work functionally identically, just with different syntax. If you want to update the docs with additional context around how to look up documentation for the 2.4 version, or you'd like to add documentation on how to add flags to the docker compose file, that would be welcome though.

**Comment by NullSoldier** [comment]
Ok so, I have a few thoughts here. I don't want to be the project that keeps their stuff stuck to older versions. I'd like to upgrade things at a reasonable pace, and I think we should ultimately upgrade our docker-compose version at some point. However, I think splitting these into legacy and not legacy doesn't feel great.

I think we should close this PR for now, and pick a point in the future to just upgrade docker-compose. I think if Ubuntu LTS upgrades docker-compose that should be a triggering event for us to do this upgrade here.

Overall, closing PR's for work contributed doesn't feel great because you put in the work, which we thank you for. If you ever have  suggestions for infrastructure you can feel free to message us in discord in [#community-dev](https://discord.com/channels/771503434028941353/831945060777852998)

**Pull request closed without merging**
