### PR TITLE
Avoid making BigUInts when comparing hashes

### PR DESCRIPTION
**Pull request by terite**
## Summary
When comparing hashes, comparing two `[u8; 32]` seems more efficient than
making a `BigUInt` to compare against target. On my laptop this improves
single-core hash rate from ~2.1 MH/s to ~4.1 MH/s.

This is my first time working in rust. I would greatly appreciate any critique, big or small, functional or aesthetic.

## Testing Plan
Added tests. Miner runs. Would like to confirm blocks are still found organically, but that's pretty time consuming.

## Breaking Change
No.

### CODE REVIEW

**Comment by mat-if** [comment]
You can probably just remove the BigUInt stuff entirely, including the dependency altogether. It comes in as a slice from Neon here https://github.com/iron-fish/ironfish/blob/master/ironfish-rust-nodejs/src/lib.rs#L95 then converted to BigUInt then passed into this fn

**Comment by dguenther** [comment]
I'm okay with merging this and doing the follow-up in a separate PR since it's not introducing any bugs, but it would be great to fix the CI warnings before merging, I think those are pretty reasonable to fix up.

**Comment by terite** [comment]
@dguenther Lint changes fixed.

@mat-if I agree that seems like a good change, but doesn't seem likely to change performance and goes beyond the scope of this PR. Mind if I leave that for someone else?

**Comment by mat-if** [comment]
Yeah, sorry, I should have been more clear, definitely fine leaving it for later

**Review by mat-if — APPROVED** [review]

**Pull request merged**
