### PR TITLE
Fixed a bug: error running "ironfish debug"

### PR DESCRIPTION
**Pull request by hamza-siddiq**
## Summary
The issue https://github.com/iron-fish/ironfish/issues/1792 reported a bug where \`ironfish debug\' command had an exception message shown. After investigating the code, it turned out that not all exceptions were handled by the catch block, which left the `dbOpen' flag variable set to true (when the database may not be actually open). This commit also contains a refactoring of the output collection functions.

## Testing Plan
Before Bug reporter:
> C:\Users\Mark>ironfish debug
Error: Database is not open. Call IDatabase.open() first

Since the issue happened to the bug reporter while running a node, I ran the node while testing.

Before Mine:

> yarn start debug
yarn run v1.22.15
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

> Iron Fish version               0.1.44 @ src
Iron Fish library               0.0.21 @ src
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 5 3600 6-Core Processor
CPU threads                     12
RAM total                       62.72 GiB
Heap total                      4.01 GiB
Node version                    v16.16.0
ironfish in PATH                true
Garbage Collector Exposed       true
Telemetry enabled               false
Node name                       
Block graffiti                  ironfishup
Done in 1.81s.

After mine:

> yarn start debug
yarn run v1.22.15
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

> Iron Fish version               0.1.44 @ src
Iron Fish library               0.0.21 @ src
Operating system                Linux x64
CPU model(s)                    AMD Ryzen 5 3600 6-Core Processor
CPU threads                     12
RAM total                       62.72 GiB
Heap total                      4.01 GiB
Node version                    v16.16.0
ironfish in PATH                true
Garbage Collector Exposed       true
Telemetry enabled               false
Node name                       
Block graffiti                  ironfishup
Done in 1.81s.

## Breaking Change
Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.
No
```
[ ] Yes
```
graffiti: ironfishup

### CODE REVIEW

**Comment by lwisne** [comment]
Please show output before and after that you tested this.

**Comment by hamza-siddiq** [comment]
Thanks @lwisne i'll work on that

**Comment by hamza-siddiq** [comment]
@lwisne I have edited the description, and posted the output requested

**Comment by lwisne** [comment]
You don't appear to be fixing the error in the linked bug?

**Comment by hamza-siddiq** [comment]
@lwisne . That's because the bug doesn't happen on my computer as you can see in my before output, most probably doesn't happens on yours as well when you run start debug, hence, why it's most probably still not verified. But it could happen in some cases, as reported by the bug reporter.

Since not all exceptions are handled in the catch block in the before code, this code should care of it. In my case though, the error never happens in both the before or after case, so it never gets caught. But if the error ever happens, and when the error happens in cases like the bug reporter, the catch block should now take care of it. The testing shows that when it runs on my or your computer, it should work fine, when there is no exception to handle.

Is there a way to make the bug appear so the catch block runs. I can't really think of a way, but if you can, please let me know, and I'll help with the testing there as well?

**Comment by lwisne** [comment]
I'm going to save you the trouble - this does not fix bug 1792, or really anything at all.

You literally posted the same output twice as your before/after.

Closing, and please consider people's time when opening up these kinds of spurious reviews.

**Comment by hamza-siddiq** [comment]
I posted that output a while ago. I'll post the new output in a bit, and you'll know what I mean

**Comment by hamza-siddiq** [comment]
@lwisne you are right. I had opened this issue before our discussion, and I noticed you're getting a bit frustrated seeing what i had done. I'm working on easier but efficient issues since we had talked. My apologies man

**Pull request closed without merging**
