### PR TITLE
Input validation for account name

### PR DESCRIPTION
**Pull request by hamza-siddiq**
## Summary
Fixes: https://github.com/iron-fish/ironfish/issues/1379

The commit validates account name in the following commands:
accounts:address
accounts:balance
accounts:create
accounts:export
accounts:notes
accounts:pay
accounts:remove
accounts:transactions
accounts:use
deposit
deposit-all
depositAll

The account name can only contain english letters, english numbers and underscores.

The regular expression used in this commit could be changed to meet other requirements.

graffiti: ironfishup

## Testing Plan
Tested successfully

## Breaking Change
Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.
No
```
[ ] Yes
```

### CODE REVIEW

**Comment by wd021** [comment]
I'm not sure this is the solution we want for the original bug, i don't think we ned to limit account names to `[^a-z^A-Z^0-9^_]`. Also, would use a const instead of rewriting it in every file and why is yarn.lock being updated?

**Comment by hamza-siddiq** [comment]
@wd021 Thanks. Would they want the account name to just exclude special characters and if yes what characters exactly?

**Comment by wd021** [comment]
i'll let someone from the team comment on this, but I'm not sure we should remove all special chars

**Comment by danield9tqh** [comment]
@hamza-siddiq I've close the original issue because we don't want to enforce validation of specific account names. We just treat them as strings. You can see the [comment](https://github.com/iron-fish/ironfish/issues/1379#issuecomment-1213518550) I left on the original issue. Sorry for the confusion. I'm going to close this PR too since the validation is not needed

**Pull request closed without merging**
