### PR TITLE
Add accounts:status and summarized status

### PR DESCRIPTION
**Pull request by hairtail**
## Summary
Feature request https://github.com/iron-fish/ironfish/issues/1914
## Testing Plan
Local test.
## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
```

### CODE REVIEW

**Comment by wd021** [comment]
is the purpose of this to show balance + scan status? seems like a huge overlap with `accounts:balance`

**Comment by lwisne** [comment]
Please create or link to an issue this solves, as described in the [new contributor guidelines](https://github.com/iron-fish/ironfish/blob/b0b91940c51009b2b00f5e58e27be89c9a5c1e39/CONTRIBUTING.md).

**Comment by hairtail** [comment]
> is the purpose of this to show balance + scan status? seems like a huge overlap with `accounts:balance`

The reason why balance output here is balance changes as `accounts:rescan` process. But I find it's not a good idea to update balance too frequently for slow getBalance. We can have a discussion here on whether balance should be here or not. Thanks for your reply.

**Comment by wd021** [comment]
imo: i don't think we need to add an `accounts:status`, but i like the idea of adding **Account Status** to `status`. The scan status is great and i would also add the account head. Your blockchain can be synced at the head, but your account chainProcessor is not there yet, like so 👇 

```
Blockchain           SYNCED @ HEAD 000000000002902c281aff7f08c5d671179b7f4e1f18b34f6b08b594d59e683c (124229)

Scanning Blocks: [========================================] 11457/11457 100% 0/sec | N/A
Scanning Complete
```

What i would add to `status` is 

Account: [SCAN STATUS], [ACCOUNT HEAD BLOCK]

**Comment by hairtail** [comment]
> imo: i don't think we need to add an `accounts:status`, but i like the idea of adding **Account Status** to `status`. The scan status is great and i would also add the account head. Your blockchain can be synced at the head, but your account chainProcessor is not there yet, like so 👇
> 
> ```
> Blockchain           SYNCED @ HEAD 000000000002902c281aff7f08c5d671179b7f4e1f18b34f6b08b594d59e683c (124229)
> 
> Scanning Blocks: [========================================] 11457/11457 100% 0/sec | N/A
> Scanning Complete
> ```
> 
> What i would add to `status` is
> 
> Account: [SCAN STATUS], [ACCOUNT HEAD BLOCK]

Get, I will update this PR asap. Thanks for your reply.

**Comment by hairtail** [comment]
> Can you paste the output of any new commands or changes to commands that you make? And surround them with triple back ticks?

Output if scan running:
```
Version              0.1.41 @ src
Node                 STARTED
Node Name            miningKing
Block Graffiti       miningKing
Memory               Heap: 62.96 MiB -> 87.80 MiB / 4.01 GiB (1.5%), RSS: 1.30 GiB (2.1%), Free: 59.82 GiB (4.8%)
P2P Network          CONNECTED - In: 6.53 KB/s, Out: 1.14 KB/s, peers 2
Mining               STARTED - 0 miners, 0 mined
Mem Pool             270 tx
Syncer               IDLE - avg time to add block 55.14 ms
Blockchain           SYNCED @ HEAD 000000000000b80f176d5defa7f19f89cafe979aeb9a610a02a527f97e0a40b7 (126514)
'''Changes
Account              Scanning: 425 / 72654 (0.6%)@ 000000000004e35c4d80b5a604dbb718b5b3a8be66b101e21dd1890c9a853ebe (72654)
'''
Telemetry            STARTED - 0 <- 2 pending
Workers              STARTED - 0 -> 1 / 47 - 0 jobs Δ, 368.19 jobs/s
```
Output if scan completed:
```
Version              0.1.41 @ src
Node                 STARTED
Node Name            miningKing
Block Graffiti       miningKing
Memory               Heap: 44.22 MiB -> 75.05 MiB / 4.01 GiB (1.1%), RSS: 1.60 GiB (2.5%), Free: 59.42 GiB (5.4%)
P2P Network          CONNECTED - In: 5.05 KB/s, Out: 2.12 KB/s, peers 2
Mining               STARTED - 0 miners, 0 mined
Mem Pool             147 tx
Syncer               IDLE - avg time to add block 55.14 ms
Blockchain           SYNCED @ HEAD 000000000000b80f176d5defa7f19f89cafe979aeb9a610a02a527f97e0a40b7 (126514)
'''Changes
Account              Scan completed (100%) @ 000000000005ac64da6a2049af9c467b96ccef4615b77b76f539be9982ddf758 (72620)
'''
Telemetry            STARTED - 0 <- 1 pending
Workers              STARTED - 0 -> 1 / 47 - -0.04 jobs Δ, 340.67 jobs/s
```

**Review by dguenther — APPROVED** [review]
Made a few changes to this to simplify it a bit. Thanks for the work!

**Pull request merged**
